### ISSUE TITLE
typescript errors upon `npm run package`

### ISSUE THREAD

**Issue by HexaField** [artbrock/clutter#30]
![Screenshot from 2022-06-09 09-45-42](https://user-images.githubusercontent.com/10372036/172735648-df97f650-3a1b-4945-a63b-fa33b444b534.png)

**Comment by bierlingm** [comment]
Is this the version in the main branch?

cc @jost-s (do you think we should update the readme with better development instructions or are those still accurate?)

**Comment by HexaField** [comment]
ah whoops, i'll try out the master branch
